
## Department of Mathematics <br> College of Arts and Sciences, Howard University<br>Math 014 (01) - Introduction to Data Science<br>Project 2 - Part 1<br>
### Student Name: Monique Bucknor       //       Due date: 04-4-2025<br> Student ID: @03133387

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#### I. Dataset Overview & Structure: 
The selected dataset contains an overview of data collected for the 2017 **Ultimate Halloween Candy Power Ranking** summarizing the compositions of 85 marketplace candies as well as comparing the sugar, price, and preferability between all of the candies. The compositional data contained information such as if the candies contained chocolate, caramel, fruit flavoring, as well as within-subject data, comparing the sugar percentage, price percentage, and overall "win" percentage (*Meaning the overall rate of preference over other candies within the researcher's survey. Specifically, participants were shown pairs of candies and asked to choose their favorite.*).

The variables are listed below: 

**Categorical Data**:
* chocolate (bool to int)
* fruity (bool to int)
* caramel (bool to int)
* peanutalmondy (bool to int)
* nougat (bool to int)
* crispedricewafer (bool to int)
* hard (bool to int)
* bar (bool to int)
* pluribus {"Is it one of many candies in a bag or box"} (bool to int)

**Numerical Data**:
* sugarpercent
* pricepercent
* winpercent

The basic shape and structure of the dataset is shown below:

In [4]:
df = pd.read_csv(r"C:\Users\pfmij\In_Class_Assignments\Monique_Bucknor_March_28\candy-data.csv")
print(f"The data's shape is {df.shape}")

The data's shape is (85, 13)

In [5]:
# Providing names for groupby
chocolate = 'chocolate'
fruity = 'fruity'
caramel = 'caramel'
nuts = 'peanutalmondy'
nougat = 'nougat'
crispedricewafer = 'crispedricewafer'
hard = 'hard'
bar = 'bar'
pluribus = 'pluribus'
sugarpercent = 'sugarpercent'
pricepercent = 'pricepercent'
winpercent = 'winpercent'

In [6]:
# Basic summary of data information
print(df.info)

<bound method DataFrame.info of                 competitorname  chocolate  fruity  caramel  peanutyalmondy  \
0                    100 Grand          1       0        1               0
1                 3 Musketeers          1       0        0               0
2                     One dime          0       0        0               0
3                  One quarter          0       0        0               0
4                    Air Heads          0       1        0               0
..                         ...        ...     ...      ...             ...
80                   Twizzlers          0       1        0               0
81                    Warheads          0       1        0               0
82        Welch's Fruit Snacks          0       1        0               0
83  Werther's Original Caramel          0       0        1               0
84                    Whoppers          1       0        0               0

    nougat  crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0        0                 1     0    1         0         0.732         0.860
1        1                 0     0    1         0         0.604         0.511
2        0                 0     0    0         0         0.011         0.116
3        0                 0     0    0         0         0.011         0.511
4        0                 0     0    0         0         0.906         0.511
..     ...               ...   ...  ...       ...           ...           ...
80       0                 0     0    0         0         0.220         0.116
81       0                 0     1    0         0         0.093         0.116
82       0                 0     0    0         1         0.313         0.313
83       0                 0     1    0         0         0.186         0.267
84       0                 1     0    0         1         0.872         0.848

    winpercent
0    66.971725
1    67.602936
2    32.261086
3    46.116505
4    52.341465
..         ...
80   45.466282
81   39.011898
82   44.375519
83   41.904308
84   49.524113

[85 rows x 13 columns]>

In [7]:
print("The first 5 rows of the data:")
print(df.head())

The first 5 rows of the data:
  competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0
1   3 Musketeers          1       0        0               0       1
2       One dime          0       0        0               0       0
3    One quarter          0       0        0               0       0
4      Air Heads          0       1        0               0       0

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860
1                 0     0    1         0         0.604         0.511
2                 0     0    0         0         0.011         0.116
3                 0     0    0         0         0.011         0.511
4                 0     0    0         0         0.906         0.511

   winpercent
0   66.971725
1   67.602936
2   32.261086
3   46.116505
4   52.341465

In [8]:
print("The last 5 rows of the data:")
print(df.tail())

The last 5 rows of the data:
                competitorname  chocolate  fruity  caramel  peanutyalmondy  \
80                   Twizzlers          0       1        0               0
81                    Warheads          0       1        0               0
82        Welch's Fruit Snacks          0       1        0               0
83  Werther's Original Caramel          0       0        1               0
84                    Whoppers          1       0        0               0

    nougat  crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
80       0                 0     0    0         0         0.220         0.116
81       0                 0     1    0         0         0.093         0.116
82       0                 0     0    0         1         0.313         0.313
83       0                 0     1    0         0         0.186         0.267
84       0                 1     0    0         1         0.872         0.848

    winpercent
80   45.466282
81   39.011898
82   44.375519
83   41.904308
84   49.524113

NOTE: The data contains **no missing values**.

#### II. Data Cleaning & Indexing:

In [11]:
# Checking for duplicate values
print(f"There are {df.duplicated().sum()} duplicate values.")

There are 0 duplicate values.

In [12]:
# Checking for null values
print(f"There are 0 null values.")
print(df.isnull().sum())

There are 0 null values.
competitorname      0
chocolate           0
fruity              0
caramel             0
peanutyalmondy      0
nougat              0
crispedricewafer    0
hard                0
bar                 0
pluribus            0
sugarpercent        0
pricepercent        0
winpercent          0
dtype: int64

In [13]:
df_new = df.copy()
#Nothing to Clean ; Indexing

**Changing "competitor name" to "Competitor Candy Name"**
<br> This change was performed for clarity.

In [15]:
df.rename(columns={'competitorname' : 'CompetitorCandyName'}, inplace=True)

**Providing Categorical Data for Clarity of Percentages/Numerical Data**

In [17]:
def categorize_win_rate(win_percent):
    
    if win_percent > 66:
        return "High Win Rate"
    elif 33 < win_percent <= 66:
        return "Medium Win Rate"
    elif win_percent <= 33:
        return "Low Win Rate"

df_new['WinRateCateg'] = df_new['winpercent'].apply(categorize_win_rate)

In [18]:
def categorize_sugar_level(sugar_percent):
    
    if sugar_percent > 0.66:
        return "High Sugar Level"
    elif 0.33 < sugar_percent <= 0.66:
        return "Medium Sugar Level"
    elif sugar_percent <= 0.33:
        return "Low Sugar Level"

df_new['SugarLevel'] = df_new['sugarpercent'].apply(categorize_sugar_level)

In [19]:
def categorize_price(price_percent):
    
    if price_percent > 0.66:
        return "Expensive"
    elif 0.33 < price_percent <= 0.66:
        return "Average Price"
    elif price_percent <= 0.33:
        return "Cheaper"

df_new['Price Comparison'] = df_new['pricepercent'].apply(categorize_price)

In [20]:
#Reviewing Indexed/Cleaned Data
df_new

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,WinRateCateg,SugarLevel,Price Comparison
0,100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,High Win Rate,High Sugar Level,Expensive
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,High Win Rate,Medium Sugar Level,Average Price
2,One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,Low Win Rate,Low Sugar Level,Cheaper
3,One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,Medium Win Rate,Low Sugar Level,Average Price
4,Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,Medium Win Rate,High Sugar Level,Average Price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Twizzlers,0,1,0,0,0,0,0,0,0,0.220,0.116,45.466282,Medium Win Rate,Low Sugar Level,Cheaper
81,Warheads,0,1,0,0,0,0,1,0,0,0.093,0.116,39.011898,Medium Win Rate,Low Sugar Level,Cheaper
82,Welch's Fruit Snacks,0,1,0,0,0,0,0,0,1,0.313,0.313,44.375519,Medium Win Rate,Low Sugar Level,Cheaper
83,Werther's Original Caramel,0,0,1,0,0,0,1,0,0,0.186,0.267,41.904308,Medium Win Rate,Low Sugar Level,Cheaper
84,Whoppers,1,0,0,0,0,1,0,0,1,0.872,0.848,49.524113,Medium Win Rate,High Sugar Level,Expensive

In [21]:
# Save as CSV
df_new.to_csv("cleaned_candy_data.csv", index=False)

#### III. Descriptive Statistics

Some things to note from summary statistics of data:
* Chocolate and Fruity flavors are equally common (Chocolate = 43.5% of candies in list contain chocolate ; Fruity = 44.7% of candies in list contain fruity flavor)
* Caramel/Nuts/Nougat/CrispedRiceWafer, on average, are less common, they appear from 8.2% to 16.5% of the candies.
* Bar candies (24.7%) are less common than pluribus (51.8%)
* A small group of candies (Those that have a win percentage above 59.9%) are fairly more popular than the majority of the candies. (Top 25% ; Those below a winrate of 59.9% fall within the majority of the candies: 75%)

In [24]:
df_new.describe()

,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent
count,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000
mean,0.435294,0.447059,0.164706,0.164706,0.082353,0.082353,0.176471,0.247059,0.517647,0.478647,0.468882,50.316764
std,0.498738,0.500140,0.373116,0.373116,0.276533,0.276533,0.383482,0.433861,0.502654,0.282778,0.285740,14.714357
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011000,0.011000,22.445341
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.220000,0.255000,39.141056
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.465000,0.465000,47.829754
75%,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.732000,0.651000,59.863998
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.988000,0.976000,84.180290

In [25]:
print(r"44/85 candies come in multiples. 41/85 do not.")
print(df[pluribus].value_counts())

44/85 candies come in multiples. 41/85 do not.
pluribus
1    44
0    41
Name: count, dtype: int64

In [26]:
print(r"15/85 candies are hard candies. 70/85 are not.")
print(df[hard].value_counts())

15/85 candies are hard candies. 70/85 are not.
hard
0    70
1    15
Name: count, dtype: int64

**Grouping compositional data & Grouping numerical data**

In grouping the fruity and chocolate candies, those candies with only chocolate characteristics had the highest average winrate. I also found that those with neither had the lowest. <br>
In grouping the numerical data, I found that no individual candy had the same average win rate, sugar level, price percentage, or any combination of similarities. Even when rounding wiht 5 decimal places, each of the candies were unique!

In [29]:
# Grouping by Chocolate and Fruity as they are the main flavorings as per our summary statistics.
df_categ = df_new.groupby(['chocolate', 'fruity'])[['sugarpercent', 'pricepercent', 'winpercent']].mean()
df_categ = df_categ.reset_index()
print(df_categ)

   chocolate  fruity  sugarpercent  pricepercent  winpercent
0          0       0      0.415000      0.376909   35.932801
1          0       1      0.464216      0.332946   43.988311
2          1       0      0.509444      0.640694   61.253165
3          1       1      0.604000      0.325000   48.982651

In [30]:
df_new['sugarpercent_rounded'] = df_new['sugarpercent'].round(5)
df_new['pricepercent_rounded'] = df_new['pricepercent'].round(5)
df_new['winpercent_rounded'] = df_new['winpercent'].round(5)

df_num = df_new.groupby(['sugarpercent_rounded', 'pricepercent_rounded', 'winpercent_rounded']).size()
df_num

sugarpercent_rounded  pricepercent_rounded  winpercent_rounded
0.011                 0.116                 32.26109              1
                      0.511                 46.11650              1
0.034                 0.279                 81.86626              1
0.046                 0.104                 39.14106              1
                      0.325                 24.52499              1
                                                                 ..
0.941                 0.220                 55.10370              1
                                            63.08514              1
0.965                 0.767                 33.43755              1
                      0.860                 64.35334              1
0.988                 0.651                 72.88790              1
Length: 85, dtype: int64

In [31]:
df_num.value_counts()

1    85
Name: count, dtype: int64

#### IV. Observations & Next Steps
**Conclusion/Summary:** This data analysis provides valuable insights into how key candy characteristics correlate with sugar content, price, and preferability. From the data, we can tell that chocolate-based products, in general, have higher sugar percentages and are more preferable in comparison to other fruity candy options.

These findings indicate a distinct relationship between flavoring choices and product characteristics, which could be helpful in making decisions about product offerings or targeting specific consumer preferences. Given that the chocolate-based products show a stronger performance in win percentages, future analysis could explore whether other factors may contribute to their higher performance. This may allow companies to refine their understanding of consumer preferences.

**Next Steps:** I would like to explore using a bar graph the count of unique values within the categorical values, making it easier for readers to see the ratio of types of candies (within our 85 candies in the data set). I would also like to see the WinPercentages within my visualization as it would make the numbers more clear to understand which candy is most preferable to least preferable. To add on, regarding Win Percentages, it would be intriguing to visualize if the presence of chocolate/caramel/fruit-flavoring etc. influences (or has any correlation) with the preferability of the candy.

#### Dataset Source (References):

FiveThirtyEight Candy Power Ranking Dataset:
["https://www.kaggle.com/datasets/fivethirtyeight/fivethirtyeight-candy-power-ranking-dataset/data"]